---
Name: dataobjectlogger
After: '*'
---
SilverStripe\ORM\DB:
  DataObjectLoggerLongDB:
    type: MySQLDatabase
    server: "`DATA_OBJECT_LOGGER_LONG_HOST`"
    database: "`DATA_OBJECT_LOGGER_LONG_DATABASE`"
    username: "`DATA_OBJECT_LOGGER_LONG_USER`"
    password: "`DATA_OBJECT_LOGGER_LONG_PASSWORD`"
    port: "`DATA_OBJECT_LOGGER_LONG_PORT`"

Gurucomkz\DataObjectLogger\LoggingExtension:
  quick_access_days: 30
  quick_to_long_batch: 300
  quick_to_long_batch_number: 30
  retain_days: 200
  purge_cron: "0 * * * *" # set to false to disable
  excluded_classes:
    - Gurucomkz\DataObjectLogger\ActivityLogEntry
    - SilverStripe\Security\RememberLoginHash
    - SilverStripe\Security\LoginAttempt
    - SilverStripe\Security\MemberPassword
    - SilverStripe\Versioned\ChangeSetItem
    - SilverStripe\Versioned\ChangeSet
    - DNADesign\Elemental\Models\ElementalArea
    - SilverStripe\Assets\Image
    - SilverStripe\Assets\File
    - SilverStripe\Assets\Folder
    - SilverStripe\Assets\Shortcodes\FileLink
    - gorriecoe\Menu\Models\MenuSet
    - SilverStripe\CronTask\CronTaskStatus

SilverStripe\ORM\DataObject:
  extensions:
    - Gurucomkz\DataObjectLogger\LoggingExtension

SilverStripe\Forms\GridField\GridFieldDetailForm_ItemRequest:
  extensions:
    - Gurucomkz\DataObjectLogger\GridFieldDetailFormExtension
